<?php

namespace Blogger\BlogBundle\Entity\Repository;

/**
 * bidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bidRepository extends \Doctrine\ORM\EntityRepository{
    public function getBidOnIdUser($user_id){
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.user = :user_id')
            ->setParameter('user_id', $user_id);
        return $qb->getQuery()->getResult();
    }

    public function getAll2(){
        $qb = $this->createQueryBuilder('r')
            ->select('r');
        return $qb->getQuery()->getResult();
    }
}
