bid_index:
    path:     /
    defaults: { _controller: "MOVYKrBundle:bid:index" }
    methods:  GET

bid_show:
    path:     /{id}/show
    defaults: { _controller: "MOVYKrBundle:bid:show" }
    methods:  GET

bid_new:
    path:     /new
    defaults: { _controller: "MOVYKrBundle:bid:new" }
    methods:  [GET, POST]

bid_edit:
    path:     /{id}/edit
    defaults: { _controller: "MOVYKrBundle:bid:edit" }
    methods:  [GET, POST]

bid_delete:
    path:     /{id}/delete
    defaults: { _controller: "MOVYKrBundle:bid:delete" }
    methods:  DELETE
