<?php

namespace MOVY\KrBundle\Repository;

/**
 * bidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bidRepository extends \Doctrine\ORM\EntityRepository
{
}
