<?php

namespace MOVY\KrBundle\Repository;

/**
 * executorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class executorRepository extends \Doctrine\ORM\EntityRepository
{
}
